channels:
   - conda-forge
   - bioconda
   - defaults
dependencies:
   - snakemake-minimal=7.20.0
   - blast=2.12.0
   - curl=7.86.0
   - entrez-direct=16.2
   - foldseek=3.915ef7d
   - hmmer=3.3.2
   - mafft=7.508
   - r-bio3d=2.4_3
   - r-tidyverse=1.3.2
   - r-showtext=0.9
